### PR TITLE
🔀 🦺 changed maxLength rule

### LINKED ISSUE #96: Fehlermeldung beim Erstellen eines Meldezeitraums wenn der Name 255 Zeichen lang ist
**Describe the bug**
grafik

**To Reproduce**
- Mit einem user der Rolle Ausbildungsleitung auf Meldezeitraum gehen
- folgenden Text einfügen: `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata`
  - sind genau 255 Zeichen

**Expected behavior**
Auf Grund der Fehlermeldung würde ich davon ausgehen dass der Text angenommen werden sollte da er genau 255 Zeichen lang ist.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10
 - Browser FF
 - Version 102

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by LuisEinig**
changed maxLength rule to include last char, e.g. maxlength=5, 5 chars allowed and not 4

**Reference:**

fixes #96 

Notifying additional team members:

@mirrodi @MrSebastian @AnHo314

### CODE REVIEW

**Review by Tuckerle — APPROVED** [review]

File: praktikumsplaner-frontend/frontend/src/composables/rules.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ export function useRules() {
 
     function maxLengthRule(length: number, message = "error") {
         return (value: string) =>
-            (value != null && value.length < length) || message;
+            (value != null && value.length <= length) || message;
```
Comment (MrSebastian) [inline praktikumsplaner-frontend/frontend/src/composables/rules.ts:8]: pls some tests

File: praktikumsplaner-frontend/frontend/tests/unit/rules.spec.ts [hunk 2]
```diff
@@ -49,3 +48,21 @@ describe("rules test", () => {
         expect(txtRule(undefined)).toBe(errorMessage);
     });
 });
+describe("rules maxLength test", () => {
```
Comment (MrSebastian) [inline praktikumsplaner-frontend/frontend/tests/unit/rules.spec.ts:51]: the `null` case is not covered

File: praktikumsplaner-frontend/frontend/tests/unit/rules.spec.ts [hunk 3]
```diff
@@ -49,3 +48,30 @@ describe("rules test", () => {
...
+
+        expect(txtRule(txt11)).toBe(errorMessage);
+    });
+    it("tests maxLengthRule return error", () => {
+        const validationRules = useRules();
+
+        const txtRule = validationRules.maxLengthRule(10, errorMessage);
+
+        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+        // @ts-ignore
```
Comment (MrSebastian) [inline praktikumsplaner-frontend/frontend/tests/unit/rules.spec.ts:74]: with that ignore comments the problems got hidden not solved. Please fix the problem.

**Review by MrSebastian — CHANGES_REQUESTED** [review]

**Review by MrSebastian — APPROVED** [review]
